In [9]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [10]:
# Imports
import torch.nn as nn

In [11]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [12]:
X = torch.from_numpy(inputs)
Y = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [13]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [14]:
# Define dataset
dataset = torch.utils.data.TensorDataset(X,Y)

In [15]:
# Define data loader
trainloader = torch.utils.data.DataLoader(dataset,batch_size=10)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [17]:
# Define model
model = nn.Linear(X.shape[1],Y.shape[1])
print(model.state_dict())
model.parameters()

OrderedDict([('weight', tensor([[ 0.0560,  0.1162, -0.3459],
        [ 0.2920,  0.4308, -0.0164]])), ('bias', tensor([ 0.4367, -0.3620]))])


<generator object Module.parameters at 0x7fc66d94ee50>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [18]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=1e-4)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [19]:
# Import nn.functional
import torch.nn.functional as F

In [20]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
#loss = loss_fn(? , ?)
#print(loss)

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [21]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in trainloader:
            # Generate predictions
            pred = model(xb)
            loss = loss_fn(yb,pred)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
        print('Training loss: ', loss_fn(model(X), Y))

In [22]:
# Train the model for 100 epochs
fit(100 , model , loss_fn, optimizer)

Training loss:  tensor(2008.0050, grad_fn=<MseLossBackward>)
Training loss:  tensor(947.6615, grad_fn=<MseLossBackward>)
Training loss:  tensor(501.9972, grad_fn=<MseLossBackward>)
Training loss:  tensor(303.7248, grad_fn=<MseLossBackward>)
Training loss:  tensor(207.5368, grad_fn=<MseLossBackward>)
Training loss:  tensor(155.3599, grad_fn=<MseLossBackward>)
Training loss:  tensor(123.5402, grad_fn=<MseLossBackward>)
Training loss:  tensor(102.1064, grad_fn=<MseLossBackward>)
Training loss:  tensor(86.6069, grad_fn=<MseLossBackward>)
Training loss:  tensor(74.8760, grad_fn=<MseLossBackward>)
Training loss:  tensor(65.7403, grad_fn=<MseLossBackward>)
Training loss:  tensor(58.4893, grad_fn=<MseLossBackward>)
Training loss:  tensor(52.6515, grad_fn=<MseLossBackward>)
Training loss:  tensor(47.8929, grad_fn=<MseLossBackward>)
Training loss:  tensor(43.9677, grad_fn=<MseLossBackward>)
Training loss:  tensor(40.6911, grad_fn=<MseLossBackward>)
Training loss:  tensor(37.9219, grad_fn=<MseLos

In [23]:
# Generate predictions
preds = model(X)
preds

tensor([[ 57.3349,  70.3534],
        [ 81.3518,  99.8273],
        [120.3664, 134.8031],
        [ 21.5444,  37.5369],
        [100.2491, 117.2957],
        [ 57.3349,  70.3534],
        [ 81.3518,  99.8273],
        [120.3664, 134.8031],
        [ 21.5444,  37.5369],
        [100.2491, 117.2957],
        [ 57.3349,  70.3534],
        [ 81.3518,  99.8273],
        [120.3664, 134.8031],
        [ 21.5444,  37.5369],
        [100.2491, 117.2957]], grad_fn=<AddmmBackward>)

In [24]:
# Compare with targets
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

Now we can define the model, optimizer and loss function exactly as before.

In [ ]:
#fit(?,?,?,?)

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

EX-1

In [25]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()

In [26]:
from sklearn.model_selection import train_test_split

X_Train,X_Test,Y_Train,Y_Test = train_test_split(inputs,targets,test_size=0.2,random_state=139)

In [27]:
model1.fit(X_Train,Y_Train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
Y_pred = model1.predict(X_Test)

In [29]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_Test,Y_pred))
Y_pred,Y_Test

0.45185834


(array([[118.66335 , 133.02359 ],
        [ 20.867573,  37.079365],
        [ 57.14113 ,  69.92001 ]], dtype=float32), array([[119., 133.],
        [ 22.,  37.],
        [ 56.,  70.]], dtype=float32))